# Generated by Django 5.2.3 on 2025-06-25 16:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(verbose_name='Número')),
                ('tipo', models.CharField(choices=[('CASA', 'Casa'), ('APARTAMENTO', 'Apartamento'), ('AREA_COMUM', 'Área Comum')], max_length=12, verbose_name='Tipo')),
            ],
            options={
                'verbose_name': 'Endereço',
                'verbose_name_plural': 'Endereços',
            },
        ),
        migrations.CreateModel(
            name='Ocorrencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50, verbose_name='Título')),
                ('descricao', models.TextField(max_length=1000, verbose_name='Descrição')),
                ('situacao', models.CharField(choices=[('AGUARDANDO', 'Aguardando'), ('CIENTE', 'Ciente'), ('RESOLVIDO', 'Resolvido')], default='AGUARDANDO', max_length=10, verbose_name='Situação')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
            ],
            options={
                'verbose_name': 'Ocorrência',
                'verbose_name_plural': 'Ocorrências',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('cpf', models.CharField(max_length=11, primary_key=True, serialize=False, verbose_name='CPF')),
                ('nome_completo', models.CharField(max_length=100, verbose_name='Nome Completo')),
                ('data_nascimento', models.DateField(verbose_name='Data de Nascimento')),
                ('email', models.EmailField(blank=True, max_length=50, null=True, unique=True, verbose_name='E-mail')),
            ],
            options={
                'verbose_name': 'Pessoa',
                'verbose_name_plural': 'Pessoas',
                'ordering': ['nome_completo'],
            },
        ),
        migrations.CreateModel(
            name='RegistroFuncionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(choices=[('SINDICO', 'Síndico'), ('ADMINISTRADOR', 'Administrador'), ('PORTEIRO', 'Porteiro'), ('SERVICOS_GERAIS', 'Serviços Gerais')], max_length=20, verbose_name='Cargo')),
                ('data_admissao', models.DateField(verbose_name='Data de Admissão')),
                ('data_demissao', models.DateField(blank=True, null=True, verbose_name='Data de Demissão')),
            ],
            options={
                'verbose_name': 'Registro de Funcionário',
                'verbose_name_plural': 'Registros de Funcionários',
                'ordering': ['-data_admissao'],
            },
        ),
        migrations.CreateModel(
            name='RegistroMorador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.DateField(verbose_name='Início da Residência')),
                ('fim', models.DateField(blank=True, null=True, verbose_name='Fim da Residência')),
            ],
            options={
                'verbose_name': 'Registro de Morador',
                'verbose_name_plural': 'Registros de Moradores',
                'ordering': ['-inicio'],
            },
        ),
        migrations.CreateModel(
            name='RegistroPonto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.DateTimeField(verbose_name='Início do Turno')),
                ('fim', models.DateTimeField(blank=True, null=True, verbose_name='Fim do Turno')),
            ],
            options={
                'verbose_name': 'Registro de Ponto',
                'verbose_name_plural': 'Registros de Ponto',
                'ordering': ['-inicio'],
            },
        ),
        migrations.CreateModel(
            name='RegistroProprietario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_compra', models.DateField(verbose_name='Data da Compra')),
                ('data_venda', models.DateField(blank=True, null=True, verbose_name='Data da Venda')),
            ],
            options={
                'verbose_name': 'Registro de Proprietário',
                'verbose_name_plural': 'Registros de Proprietários',
                'ordering': ['-data_compra'],
            },
        ),
        migrations.CreateModel(
            name='RegistroVisitante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_chegada', models.DateTimeField(verbose_name='Data e Hora da Chegada')),
            ],
            options={
                'verbose_name': 'Registro de Visitante',
                'verbose_name_plural': 'Registros de Visitantes',
                'ordering': ['-data_chegada'],
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_reserva', models.DateTimeField(verbose_name='Data e Hora da Reserva')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('situacao', models.CharField(choices=[('AGUARDANDO', 'Aguardando Confirmação'), ('CONFIRMADO', 'Confirmado'), ('EFETIVADO', 'Efetivado (Utilizado)')], default='AGUARDANDO', max_length=15, verbose_name='Situação')),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
                'ordering': ['-data_reserva'],
            },
        ),
        migrations.CreateModel(
            name='Telefone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=15, verbose_name='Número')),
                ('tipo', models.CharField(choices=[('FIXO', 'Fixo'), ('CELULAR', 'Celular')], default='CELULAR', max_length=7, verbose_name='Tipo')),
            ],
            options={
                'verbose_name': 'Telefone',
                'verbose_name_plural': 'Telefones',
            },
        ),
        migrations.CreateModel(
            name='Apartamento',
            fields=[
                ('endereco_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.endereco')),
                ('andar', models.CharField(max_length=50, verbose_name='Andar')),
                ('predio', models.CharField(blank=True, max_length=50, null=True, verbose_name='Prédio/Bloco')),
            ],
            options={
                'verbose_name': 'Apartamento',
                'verbose_name_plural': 'Apartamentos',
            },
            bases=('core.endereco',),
        ),
        migrations.CreateModel(
            name='AreaComum',
            fields=[
                ('endereco_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.endereco')),
                ('nome', models.CharField(max_length=20, verbose_name='Nome da Área')),
                ('reservavel', models.BooleanField(default=False, verbose_name='É Reservável?')),
                ('descricao', models.TextField(max_length=1000, verbose_name='Descrição')),
                ('local', models.CharField(blank=True, max_length=100, null=True, verbose_name='Localização')),
                ('lotacao', models.IntegerField(blank=True, null=True, verbose_name='Lotação Máxima')),
            ],
            options={
                'verbose_name': 'Área Comum',
                'verbose_name_plural': 'Áreas Comuns',
            },
            bases=('core.endereco',),
        ),
        migrations.CreateModel(
            name='Casa',
            fields=[
                ('endereco_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.endereco')),
                ('rua', models.CharField(max_length=50, verbose_name='Rua')),
                ('conjunto', models.CharField(blank=True, max_length=50, null=True, verbose_name='Conjunto')),
            ],
            options={
                'verbose_name': 'Casa',
                'verbose_name_plural': 'Casas',
            },
            bases=('core.endereco',),
        ),
    ]
