# Generated by Django 5.2.3 on 2025-06-24 20:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('cpf', models.CharField(max_length=11, primary_key=True, serialize=False, verbose_name='CPF')),
                ('nome_completo', models.CharField(max_length=100, verbose_name='Nome Completo')),
                ('data_nascimento', models.DateField(verbose_name='Data de Nascimento')),
                ('email', models.EmailField(blank=True, max_length=50, null=True, unique=True, verbose_name='E-mail')),
                ('usuario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pessoa', to=settings.AUTH_USER_MODEL, verbose_name='Usuário do Sistema')),
            ],
            options={
                'verbose_name': 'Pessoa',
                'verbose_name_plural': 'Pessoas',
                'ordering': ['nome_completo'],
            },
        ),
    ]
