# Generated by Django 5.2.3 on 2025-06-25 16:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='usuario',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pessoa', to=settings.AUTH_USER_MODEL, verbose_name='Usuário do Sistema'),
        ),
        migrations.AddField(
            model_name='registrofuncionario',
            name='pessoa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_funcionario', to='core.pessoa', verbose_name='Pessoa'),
        ),
        migrations.AddField(
            model_name='ocorrencia',
            name='funcionario_responsavel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ocorrencias_atendidas', to='core.registrofuncionario', verbose_name='Funcionário Responsável'),
        ),
        migrations.AddField(
            model_name='registromorador',
            name='endereco',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registros_morador', to='core.endereco', verbose_name='Endereço'),
        ),
        migrations.AddField(
            model_name='registromorador',
            name='pessoa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_morador', to='core.pessoa', verbose_name='Pessoa'),
        ),
        migrations.AddField(
            model_name='ocorrencia',
            name='morador_relator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ocorrencias_abertas', to='core.registromorador', verbose_name='Morador Relator'),
        ),
        migrations.AddField(
            model_name='registroponto',
            name='funcionario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_ponto', to='core.registrofuncionario', verbose_name='Funcionário'),
        ),
        migrations.AddField(
            model_name='registroponto',
            name='local',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registros_ponto_local', to='core.endereco', verbose_name='Local do Ponto'),
        ),
        migrations.AddField(
            model_name='registroproprietario',
            name='endereco',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registros_proprietario', to='core.endereco', verbose_name='Endereço'),
        ),
        migrations.AddField(
            model_name='registroproprietario',
            name='pessoa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_proprietario', to='core.pessoa', verbose_name='Pessoa'),
        ),
        migrations.AddField(
            model_name='registrovisitante',
            name='endereco_destino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='visitas_recebidas', to='core.endereco', verbose_name='Endereço de Destino'),
        ),
        migrations.AddField(
            model_name='registrovisitante',
            name='morador_responsavel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='visitas_autorizadas', to='core.registromorador', verbose_name='Morador Responsável'),
        ),
        migrations.AddField(
            model_name='registrovisitante',
            name='pessoa_visitante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitas_feitas', to='core.pessoa', verbose_name='Visitante'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='funcionario_aprovador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservas_aprovadas', to='core.registrofuncionario', verbose_name='Funcionário Aprovador'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='morador_solicitante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas_feitas', to='core.registromorador', verbose_name='Morador Solicitante'),
        ),
        migrations.AddField(
            model_name='telefone',
            name='endereco',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='telefones', to='core.endereco', verbose_name='Endereço'),
        ),
        migrations.AddField(
            model_name='telefone',
            name='pessoa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='telefones', to='core.pessoa', verbose_name='Pessoa'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='area_comum',
            field=models.ForeignKey(limit_choices_to={'reservavel': True}, on_delete=django.db.models.deletion.PROTECT, related_name='reservas', to='core.areacomum', verbose_name='Área Comum'),
        ),
        migrations.AddConstraint(
            model_name='telefone',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('pessoa__isnull', False), ('endereco__isnull', True)), models.Q(('pessoa__isnull', True), ('endereco__isnull', False)), _connector='OR'), name='telefone_pertence_a_pessoa_ou_endereco'),
        ),
    ]
