# Generated by Django 5.2.3 on 2025-06-25 07:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_endereco_polymorphic_ctype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='endereco',
            name='polymorphic_ctype',
        ),
        migrations.CreateModel(
            name='RegistroFuncionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(choices=[('SINDICO', 'Síndico'), ('ADMINISTRADOR', 'Administrador'), ('PORTEIRO', 'Porteiro'), ('SERVICOS_GERAIS', 'Serviços Gerais')], max_length=20, verbose_name='Cargo')),
                ('data_admissao', models.DateField(verbose_name='Data de Admissão')),
                ('data_demissao', models.DateField(blank=True, null=True, verbose_name='Data de Demissão')),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_funcionario', to='core.pessoa', verbose_name='Pessoa')),
            ],
            options={
                'verbose_name': 'Registro de Funcionário',
                'verbose_name_plural': 'Registros de Funcionários',
                'ordering': ['-data_admissao'],
            },
        ),
        migrations.CreateModel(
            name='RegistroMorador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.DateField(verbose_name='Início da Residência')),
                ('fim', models.DateField(blank=True, null=True, verbose_name='Fim da Residência')),
                ('endereco', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registros_morador', to='core.endereco', verbose_name='Endereço')),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_morador', to='core.pessoa', verbose_name='Pessoa')),
            ],
            options={
                'verbose_name': 'Registro de Morador',
                'verbose_name_plural': 'Registros de Moradores',
                'ordering': ['-inicio'],
            },
        ),
        migrations.CreateModel(
            name='RegistroProprietario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_compra', models.DateField(verbose_name='Data da Compra')),
                ('data_venda', models.DateField(blank=True, null=True, verbose_name='Data da Venda')),
                ('endereco', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registros_proprietario', to='core.endereco', verbose_name='Endereço')),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_proprietario', to='core.pessoa', verbose_name='Pessoa')),
            ],
            options={
                'verbose_name': 'Registro de Proprietário',
                'verbose_name_plural': 'Registros de Proprietários',
                'ordering': ['-data_compra'],
            },
        ),
        migrations.CreateModel(
            name='RegistroVisitante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_chegada', models.DateTimeField(verbose_name='Data e Hora da Chegada')),
                ('data_saida', models.DateTimeField(blank=True, null=True, verbose_name='Data e Hora da Saída')),
                ('endereco_destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='visitas_recebidas', to='core.endereco', verbose_name='Endereço de Destino')),
                ('morador_responsavel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='visitas_autorizadas', to='core.registromorador', verbose_name='Morador Responsável')),
                ('pessoa_visitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitas_feitas', to='core.pessoa', verbose_name='Visitante')),
            ],
            options={
                'verbose_name': 'Registro de Visitante',
                'verbose_name_plural': 'Registros de Visitantes',
                'ordering': ['-data_chegada'],
            },
        ),
    ]
