# Generated by Django 5.2.3 on 2025-06-25 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_endereco_polymorphic_ctype_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrovisitante',
            name='data_saida',
        ),
        migrations.CreateModel(
            name='Ocorrencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50, verbose_name='Título')),
                ('descricao', models.TextField(max_length=1000, verbose_name='Descrição')),
                ('situacao', models.CharField(choices=[('AGUARDANDO', 'Aguardando'), ('CIENTE', 'Ciente'), ('RESOLVIDO', 'Resolvido')], default='AGUARDANDO', max_length=10, verbose_name='Situação')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('funcionario_responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ocorrencias_atendidas', to='core.registrofuncionario', verbose_name='Funcionário Responsável')),
                ('morador_relator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ocorrencias_abertas', to='core.registromorador', verbose_name='Morador Relator')),
            ],
            options={
                'verbose_name': 'Ocorrência',
                'verbose_name_plural': 'Ocorrências',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='RegistroPonto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.DateTimeField(verbose_name='Início do Turno')),
                ('fim', models.DateTimeField(blank=True, null=True, verbose_name='Fim do Turno')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_ponto', to='core.registrofuncionario', verbose_name='Funcionário')),
                ('local', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registros_ponto_local', to='core.endereco', verbose_name='Local do Ponto')),
            ],
            options={
                'verbose_name': 'Registro de Ponto',
                'verbose_name_plural': 'Registros de Ponto',
                'ordering': ['-inicio'],
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_reserva', models.DateTimeField(verbose_name='Data e Hora da Reserva')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('situacao', models.CharField(choices=[('AGUARDANDO', 'Aguardando Confirmação'), ('CONFIRMADO', 'Confirmado'), ('EFETIVADO', 'Efetivado (Utilizado)')], default='AGUARDANDO', max_length=15, verbose_name='Situação')),
                ('area_comum', models.ForeignKey(limit_choices_to={'reservavel': True}, on_delete=django.db.models.deletion.PROTECT, related_name='reservas', to='core.areacomum', verbose_name='Área Comum')),
                ('funcionario_aprovador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservas_aprovadas', to='core.registrofuncionario', verbose_name='Funcionário Aprovador')),
                ('morador_solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas_feitas', to='core.registromorador', verbose_name='Morador Solicitante')),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
                'ordering': ['-data_reserva'],
            },
        ),
    ]
